services:
  - type: web
    name: javascript-challenge-api
    runtime: node
    plan: starter
    buildCommand: npm install && npx sequelize-cli db:migrate
    startCommand: chmod +x start-render.sh && ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: SLOW_DOWN_DELAY_AFTER
        value: 50
      - key: SLOW_DOWN_DELAY_MS
        value: 500
      - key: LATE_FEE_AMOUNT
        value: 500
      - key: CURRENCY
        value: NGN
      - key: DISABLE_EMAILS
        value: "true"
      - key: FRONTEND_URL
        value: "https://your-frontend-url.onrender.com"

databases:
  - name: javascript-challenge-db
    databaseName: javascript_challenge_db
    user: javascript_challenge_user
    plan: starter 